### PR TITLE
build(docker): add docker file

### PR DESCRIPTION
**Pull request by mostaphaRoudsari**
@tymokvo I invited you to ladybug-tools to be able to ask for your official review! Meanwhile this is the unofficial request for review! 😀

I haven't tested the commands inside the image more than `honeybee-vtk --help` which works! I would try to run the tests inside the Docker image as a required step to accept this PR.

related: #183 
cc: @devngc

### CODE REVIEW

**Review by tymokvo — COMMENTED** [review]
Just ran the test suite quickly and it failed with a segfault:

```console
tests/local/scene_test.py Fatal Python error: Segmentation fault

Current thread 0x00007f72d5267740 (most recent call first):
  File "/src/honeybee_vtk/assistant.py", line 162 in _export_image
  <truncated>
```

On line 162, we're calling `vtk.vtkRenderWindow.Render` which is trying to connect to an actual Xserver to render the image. 

Calling it directly returns:
```console
2021-07-08 17:58:00.233 (  22.064s) [        E893A740]vtkXOpenGLRenderWindow.:448    ERR| vtkXOpenGLRenderWindow (0x55d7accda480): bad X server connection. DISPLAY=
Aborted (core dumped)
```

We will need to find a way to get the rendering to happen "headless" in order to use this on kubernetes.

Let me know if you want me to look into getting this to work. I'm not familiar enough with VTK's internals to know what changes to request right now. Or maybe @devngc has some ideas...

**Comment by mostaphaRoudsari** [comment]
Hi @tymokvo, You are probably best situated to help with this. We have been using the library from their Python bindings. Didn't really need to get into the details about how the rendering happens until now. I'm sure [I hope] we are not the first and the only one to hit this issue.

**Comment by tymokvo** [comment]
Ok. It seems like we will need to make some source changes in order to get this to work. The changes won't really make sense in this PR.

Since the docker build is otherwise working, I would say this PR should just add a step to test in the container before pushing it. I can take over this PR for you @mostaphaRoudsari if that would help.

Do you have a timeline of when this needs to be working?

**Comment by mostaphaRoudsari** [comment]
@tymokvo, thanks! I wanted to get a sense about how much work it is first.

Before we want to hack it ourselves I would say that we should post this as a question on VTK discourse. If there is no good advice there then we can do it ourselves. @devngc, can you take care of posting the question and see if anyone else has successfully created a Docker image from VTK with the Python binding.

> I can take over this PR for you @mostaphaRoudsari if that would help.

Please do! I was expecting that this will not work easily.

In case you haven't seen it already this might also be helpful: https://github.com/lukin0110/docker-vtk-python - he has faced the same issue (https://github.com/lukin0110/docker-vtk-python/issues/1) but we might be able to reuse some of the steps from his Dockerfile if we end up building our own from source.

**Comment by tymokvo** [comment]
Someone has asked a similar question [here](https://discourse.vtk.org/t/how-to-build-vtk-on-a-supercomputer-without-x-server-and-no-root-previliges/377/4). I would say we should either follow up there, or just take the snippet there as a starting point. Though, it looks like they are suggesting using a custom build of python called `pvpython` which sounds ominous.

Otherwise, we could build our own version of VTK against OSMesa which seems to be the most "correct" way to do it.

**Comment by tymokvo** [comment]
@mostaphaRoudsari I think you will have to merge this as I cannot write. :crying_cat_face:

**Comment by mostaphaRoudsari** [comment]
@tymokvo, now you should have `write` access! Make it happen. 😀

**Pull request merged**
