### PR TITLE
Replace Paraview Glance viewer with Pollination viewer

### PR DESCRIPTION
**Pull request by NGimbal**
…updated add_data_to_viewer func

Now when using honeybee-vtk translate you get an html file that uses the lavender viewer instead of Paraview Glance! Pretty cool.

Looks like I can't added reviewers? but @mostaphaRoudsari & @devngc let me know how this looks / if anything needs to change.

### CODE REVIEW

**Review by mostaphaRoudsari — APPROVED** [review]
Hi @NGimbal! LGTM. I assigned @devngc to do the final review and merge it if it looks good to him.

This is a major step forward! Thank you.

**Review by devngc — APPROVED** [review]
Hey @NGimbal,

Looks good to me. I would suggest to add Pollination favicon and title to the template HTML.

Capture

This is a big win for the Revit plugin.

**Comment by NGimbal** [comment]
@devngc - I will make those changes, maybe on this PR or on a subsequent one. I'm still trying to figure out some Github Workflow way to automatically update this template when I update Lavender.

**Comment by devngc** [comment]
@NGimbal, sounds good. Go ahead and "rebase and merge."

**Comment by mostaphaRoudsari** [comment]
Good catch @devngc! I merged this one in but we should open an issue to make sure we don't forget about the header.

**Pull request merged**
